-- MySQL Script generated by MySQL Workbench
-- 04/05/17 18:56:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema db_trab_jfx_01
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_trab_jfx_01
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_trab_jfx_01` DEFAULT CHARACTER SET utf8 ;
USE `db_trab_jfx_01` ;

-- -----------------------------------------------------
-- Table `db_trab_jfx_01`.`tb_profissoes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_trab_jfx_01`.`tb_profissoes` (
  `cod_profissao` INT NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`cod_profissao`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_trab_jfx_01`.`tb_pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_trab_jfx_01`.`tb_pessoas` (
  `cod_pessoa` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT NOT NULL,
  `nome_pessoa` VARCHAR(45) NOT NULL,
  `data_nascimento` DATE NOT NULL,
  `cod_profissao` INT NOT NULL,
  PRIMARY KEY (`cod_pessoa`, `cod_profissao`),
  INDEX `fk_tb_pessoas_tb_profissoes_idx` (`cod_profissao` ASC),
  CONSTRAINT `fk_tb_pessoas_tb_profissoes`
    FOREIGN KEY (`cod_profissao`)
    REFERENCES `db_trab_jfx_01`.`tb_profissoes` (`cod_profissao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_trab_jfx_01`.`tb_usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_trab_jfx_01`.`tb_usuarios` (
  `cod_usuario` INT NOT NULL AUTO_INCREMENT,
  `nome_usuario` VARCHAR(45) NULL,
  `usuario` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  PRIMARY KEY (`cod_usuario`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
